apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "freebytech-corp.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "freebytech-corp.name" . }}
    helm.sh/chart: {{ include "freebytech-corp.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app: {{ include "freebytech-corp.name" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "freebytech-corp.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "freebytech-corp.name" . }}
        version: {{ .Values.image.tag }}
    spec:
      imagePullSecrets:
        - name: {{ .Values.image.imagePullSecrets }}      
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{- with .Values.env }}
          env:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          ports:
            - name: http
              containerPort: {{ .Values.service.internalPort }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /swagger/index.html
              port: http
          readinessProbe:
            httpGet:
              path: /swagger/index.html
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
