# Default values for tiv-api-budget.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: placeholder
  tag: "placeholder"
  pullPolicy: Always
  imagePullSecrets: [ "registry-regcred" ]
env:
  - name: MAIL__SMTPSERVER
    valueFrom:
      secretKeyRef:
        name: smtp-env-secrets
        key: MAIL__SMTPSERVER
  - name: MAIL__SMTPPORT
    valueFrom:
      secretKeyRef:
        name: smtp-env-secrets
        key: MAIL__SMTPPORT
  - name: MAIL__SMTPUSERNAME
    valueFrom:
      secretKeyRef:
        name: smtp-env-secrets
        key: MAIL__SMTPUSERNAME
  - name: MAIL__SMTPPASSWORD
    valueFrom:
      secretKeyRef:
        name: smtp-env-secrets
        key: MAIL__SMTPPASSWORD
  - name: MAIL__SMTPENABLESSL
    valueFrom:
      secretKeyRef:
        name: smtp-env-secrets
        key: MAIL__SMTPENABLESSL
  - name: DB__SERVERNAME
    valueFrom:
      secretKeyRef:
        name: db-env-secrets
        key: DB__SERVERNAME
  - name: DB__USERNAME
    valueFrom:
      secretKeyRef:
        name: db-env-secrets
        key: DB__USERNAME
  - name: DB__USERPASSWORD
    valueFrom:
      secretKeyRef:
        name: db-env-secrets
        key: DB__USERPASSWORD
  - name: BUDGETAPP__CLIENTROOTURL
    valueFrom:
      secretKeyRef:
        name: tiv-app-budget-secrets
        key: BUDGETAPP__CLIENTROOTURL
  - name: BUDGETAPP__STSAUDIENCE
    valueFrom:
      secretKeyRef:
        name: tiv-app-budget-secrets
        key: BUDGETAPP__STSAUDIENCE
  - name: BUDGETAPP__STSAUTHORITY
    valueFrom:
      secretKeyRef:
        name: tiv-app-budget-secrets
        key: BUDGETAPP__STSAUTHORITY
  - name: BUDGETAPP__STSCLIENTID
    valueFrom:
      secretKeyRef:
        name: tiv-app-budget-secrets
        key: BUDGETAPP__STSCLIENTID
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  type: ClusterIP
  port: 8080
  internalPort: 80

ingress:
  enabled: false
  className: ""
  annotations: 
    kubernetes.io/ingress.class: nginx
    kubernetes.io/tls-acme: "true"
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}
