# Default values for freebytech-corp.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: registry.freebytech.com/trackitsvalue/tiv-api-budget
  tag: "latest"
  pullPolicy: Always
  imagePullSecrets: "freebytech-regcred"
env:
  - name: MAIL__SMTPSERVER
    valueFrom:
      secretKeyRef:
        name: smtp-env-secrets
        key: MAIL__SMTPSERVER
  - name: MAIL__SMTPPORT
    valueFrom:
      secretKeyRef:
        name: smtp-env-secrets
        key: MAIL__SMTPPORT
  - name: MAIL__SMTPUSERNAME
    valueFrom:
      secretKeyRef:
        name: smtp-env-secrets
        key: MAIL__SMTPUSERNAME
  - name: MAIL__SMTPPASSWORD
    valueFrom:
      secretKeyRef:
        name: smtp-env-secrets
        key: MAIL__SMTPPASSWORD
  - name: MAIL__SMTPENABLESSL
    valueFrom:
      secretKeyRef:
        name: smtp-env-secrets
        key: MAIL__SMTPENABLESSL
  - name: DB__SERVERNAME
    valueFrom:
      secretKeyRef:
        name: db-env-secrets
        key: DB__SERVERNAME
  - name: DB__USERNAME
    valueFrom:
      secretKeyRef:
        name: db-env-secrets
        key: DB__USERNAME
  - name: DB__USERPASSWORD
    valueFrom:
      secretKeyRef:
        name: db-env-secrets
        key: DB__USERPASSWORD
  - name: OKTA_CLIENT_CONNECTIONTIMEOUT
    valueFrom:
      secretKeyRef:
        name: sts-env-secrets
        key: OKTA_CLIENT_CONNECTIONTIMEOUT
  - name: OKTA_CLIENT_OKTADOMAIN
    valueFrom:
      secretKeyRef:
        name: sts-env-secrets
        key: OKTA_CLIENT_OKTADOMAIN
  - name: OKTA_CLIENT_TOKEN
    valueFrom:
      secretKeyRef:
        name: sts-env-secrets
        key: OKTA_CLIENT_TOKEN
#nameOverride: ""
#fullnameOverride: ""

service:
  type: ClusterIP
  port: 5000
  internalPort: 5000

ingress:
  enabled: true
  annotations: 
    kubernetes.io/ingress.class: "nginx"
    ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    ingress.kubernetes.io/proxy-body-size: "0"
    nginx.ingress.kubernetes.io/proxy-body-size: "0"
    certmanager.k8s.io/cluster-issuer: letsencrypt-production-clusteri
    kubernetes.io/tls-acme: "true"
  paths: 
    - /
  hosts:
    - beta-api.trackitsvalue.com
  tls:
    - secretName: betaapi-trackitsvalue-tls
      hosts:
        - beta-api.trackitsvalue.com

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #  cpu: 100m
  #  memory: 128Mi
  # requests:
  #  cpu: 100m
  #  memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}
